version: 3

env:
  TYPST_ROOT: .
  TYPST_FONT_PATHS: assets/fonts

tasks:
  default:
    desc: Genera los documentos principales del trabajo de grado
    deps:
      - plan
      - thesis
      - spine-cover
      - front-cover
      - cv
  cv:
    dir: documents/cv/
    env:
      TYPST_ROOT: ../../
    desc: Genera el documento de curriculum vitae
    cmds:
      - typst compile CV.typ
      - typst compile CV.typ CV.svg
    generates:
      - CV.pdf
      - CV.svg
  spine-cover:
    dir: documents/book/
    env:
      TYPST_ROOT: ../../
    desc: Genera el lomo del libro
    cmds:
      - typst compile spine-cover.typ
    sources:
      - spine-cover.typ
      - ../../**/*.typ
    generates:
      - spine-cover.pdf
  front-cover:
    dir: documents/book/
    env:
      TYPST_ROOT: ../../
    desc: Genera la portada (tapa externa) del libro
    cmds:
      - typst compile front-cover.typ
    generates:
      - front-cover.pdf
  plan:
    dir: documents/plan/
    env:
      TYPST_ROOT: ../../
    desc: Genera el documento de plan de trabajo
    cmds:
      - typst compile TFG-PLAN.typ
    generates:
      - plan.pdf
  thesis:
    deps:
      - cv
    dir: documents/thesis/
    env:
      TYPST_ROOT: ../../
    desc: Genera la tesis o documento principal del trabajo de grado
    cmds:
      - typst compile TFG.typ
    sources:
      - "**/*.typ"
      - "../../**/*.typ"
    generates:
      - thesis.pdf
  web:
    desc: Genera los documentos correspondientes para la publicación web
    cmds:
      - mkdir -p web
      - typst compile --pdf-standard 2.0 documents/thesis/TFG.typ web/thesis.pdf
    generates:
      - web/thesis.pdf
  archival:
    desc: Genera los documentos correspondientes para fines de preservación a largo plazo
    cmds:
      - mkdir -p archival
      - typst compile --pdf-standard a-4f documents/thesis/TFG.typ archival/thesis.pdf
    generates:
      - archival/thesis.pdf
  accessibility:
    desc: Genera los documentos correspondientes con estándares de accesibilidad
    cmds:
      - mkdir -p accessibility
      - typst compile --pdf-standard ua-1 documents/thesis/TFG.typ accessibility/thesis.pdf
